gas_rics = {'CGXHVPDA': None, 'CZVTPDA': None, 'ICPATVTPDA': None, 'MIBG-WD-ES': None, 'PEGDA': None, 'PNCGDA': None,
            'POXGBASE': None, 'TRDEGSPD1': None, 'TRGBNBPD1': None, 'TRITPSVDA': None, 'TRNLTTFD1': None,
            'ZEEDA': {'def_unit': "THERM"}, 'TFMBMF0^2': None, 'TFMBMG0^2': None, 'TFMBMH0^2': None, 'TFMBMJ0^2': None,
            'TFMBMK0^2': None, 'TFMBMM0^2': None, 'TFMBMN0^2': None, 'TFMBMQ0^2': None, 'TFMBMU0^2': None,
            'TFMBMV0^2': None, 'TFMBMX0^2': None, 'TFMBMZ0^2': None, 'TFMBMF1^2': None, 'TFMBMG1^2': None,
            'TFMBMH1^2': None, 'TFMBMJ1': None, 'TFMBMK1': None, 'TFMBMM1': None, 'TFMBMN1': None, 'TFMBMQ1': None,
            'TFMBMU1': None, 'TFMBMV1': None, 'TFMBMX1': None, 'TFMBMZ1': None, 'TFMBMF2': None, 'TFMBMG2': None,
            'TFMBMH2': None, 'TFMBMJ2': None, 'TFMBMK2': None, 'TFMBMM2': None, 'TFMBMN2': None, 'TFMBMQ2': None,
            'TFMBMU2': None, 'TFMBMV2': None, 'TFMBMX2': None, 'TFMBMZ2': None, 'TFMBMF3': None, 'TFMBMG3': None,
            'TFMBMH3': None, 'TFMBMJ3': None, 'TFMBMK3': None, 'TFMBMM3': None, 'TFMBMN3': None, 'TFMBMQ3': None,
            'TFMBMU3': None, 'TFMBMV3': None, 'TFMBMX3': None, 'TFMBMZ3': None, 'TRITPSVWEND': None,
            'ICPITPSVWEND': None, 'ICPITPSVBOW': None, 'TRITPSVMc1': None, 'ICPITPSVMc1': None, 'PSVMc1': None,
            'GRFPSVMc1': None, 'ICPITPSVBOM': None, 'GRFPSVBOM': None, 'TRITPSVQc1': None, 'ICPITPSVQc1': None,
            'PSVQc1': None, 'TRITPSVQc2': None, 'ICPITPSVQc2': None, 'PSVQc2': None, 'TRITPSVQc3': None,
            'PSVQc3': None, 'PSVQc4': None, 'TRITPSVSc1': None, 'ICPITPSVSc1': None, 'PSVSc1': None, 'TRITPSVSc2': None,
            'ICPITPSVSc2': None, 'PSVSc2': None, 'TRITPSVMc2': None, 'PSVMc2': None, 'ICPITPSVMc2': None,
            'TRITPSVMc3': None, 'PSVMc3': None, 'ICPITPSVMc3': None, 'TRITPSVQc4': None, 'TRITPSVSc3': None,
            'TRITPSVYc1': None, 'PSVYc1': None, 'TRITPSVYc2': None, 'PSVYc2': None, 'TRITPSVYc3': None, 'PSVYc3': None,
            'TFSITPSVGDA': None, 'TFSITPSVGWEND': None, 'TFSITPSVGSc1': None, 'TFSITPSVGSc2': None,
            'TFSITPSVGBOW': None, 'TFSITPSVGMc1': None, 'TFSITPSVGMc2': None, 'TFSITPSVGMc3': None,
            'TFSITPSVGQc1': None, 'TFSITPSVGQc2': None, 'TFSITPSVGQc3': None, 'TFSITPSVGQc4': None,
            'TFSITPSVGYc1': None, 'TFSITPSVGYc2': None, 'TFSITPSVGYc3': None, 'TRBEZEED1': None, 'TRDENCGD1': None,
            'TRFRPEGD1': None, 'TRGBNBPWE': None, 'TRBEZEEWE': None, 'TRNLTTFWE': None, 'TRDENCGWE': None,
            'TRDEGSPWE': None, 'TRFRPEGWE': None, 'TRGBNBPMc1': None, 'TRBEZEEMc1': None, 'TRNLTTFMc1': None,
            'TRDENCGMc1': None, 'TRDEGSPMc1': None, 'TRFRPEGMc1': None, 'TRGBNBPMc2': None, 'TRBEZEEMc2': None,
            'TRNLTTFMc2': None, 'TRDENCGMc2': None, 'TRDEGSPMc2': None, 'TRFRPEGMc2': None, 'TRGBNBPMc3': None,
            'TRBEZEEMc3': None, 'TRNLTTFMc3': None, 'TRDENCGMc3': None, 'TRDEGSPMc3': None, 'TRFRPEGMc3': None,
            'TRGBNBPQc1': None, 'TRBEZEEQc1': None, 'TRNLTTFQc1': None, 'TRDENCGQc1': None, 'TRDEGSPQc1': None,
            'TRFRPEGQc1': None, 'TRGBNBPQc2': None, 'TRBEZEEQc2': None, 'TRNLTTFQc2': None, 'TRDENCGQc2': None,
            'TRDEGSPQc2': None, 'TRFRPEGQc2': None, 'TRGBNBPQc3': None, 'TRBEZEEQc3': None, 'TRNLTTFQc3': None,
            'TRDENCGQc3': None, 'TRDEGSPQc3': None, 'TRFRPEGQc3': None, 'TRGBNBPSc1': None, 'TRBEZEESc1': None,
            'TRNLTTFSc1': None, 'TRDENCGSc1': None, 'TRDEGSPSc1': None, 'TRFRPEGSc1': None, 'TRGBNBPSc2': None,
            'TRBEZEESc2': None, 'TRNLTTFSc2': None, 'TRDENCGSc2': None, 'TRDEGSPSc2': None, 'TRFRPEGSc2': None,
            'TRNLTTFYc1': None, 'TRDENCGYc1': None, 'TRDEGSPYc1': None, 'TRFRPEGYc1': None, 'TRNLTTFYc2': None,
            'TRDENCGYc2': None, 'TRDEGSPYc2': None, 'TRFRPEGYc2': None}
