_GAS_VOL = 1
_GAS_NO_VOL = 0

gas_rics = {'CGXHVPDA': {'vol': _GAS_VOL}, 'CZVTPDA': {'vol': _GAS_VOL}, 'ICPATVTPDA': {'vol': _GAS_NO_VOL},
            'MIBG-WD-ES': {'vol': _GAS_VOL}, 'PEGDA': {'vol': _GAS_VOL}, 'PNCGDA': {'vol': _GAS_VOL},
            'POXGBASE': {'vol': _GAS_VOL}, 'TRDEGSPD1': {'vol': _GAS_NO_VOL}, 'TRGBNBPD1': {'vol': _GAS_NO_VOL},
            'TRITPSVDA': {'vol': _GAS_NO_VOL}, 'TRNLTTFD1': {'vol': _GAS_NO_VOL},
            'ZEEDA': {'vol': _GAS_VOL, 'def_unit': "THERM"}, 'TFMBMF0^2': {'vol': _GAS_VOL},
            'TFMBMG0^2': {'vol': _GAS_VOL}, 'TFMBMH0^2': {'vol': _GAS_VOL}, 'TFMBMJ0^2': {'vol': _GAS_VOL},
            'TFMBMK0^2': {'vol': _GAS_VOL}, 'TFMBMM0^2': {'vol': _GAS_VOL}, 'TFMBMN0^2': {'vol': _GAS_VOL},
            'TFMBMQ0^2': {'vol': _GAS_VOL}, 'TFMBMU0^2': {'vol': _GAS_VOL}, 'TFMBMV0^2': {'vol': _GAS_VOL},
            'TFMBMX0^2': {'vol': _GAS_VOL}, 'TFMBMZ0^2': {'vol': _GAS_VOL}, 'TFMBMF1^2': {'vol': _GAS_VOL},
            'TFMBMG1^2': {'vol': _GAS_VOL}, 'TFMBMH1^2': {'vol': _GAS_VOL}, 'TFMBMJ1': {'vol': _GAS_VOL},
            'TFMBMK1': {'vol': _GAS_VOL}, 'TFMBMM1': {'vol': _GAS_VOL}, 'TFMBMN1': {'vol': _GAS_VOL},
            'TFMBMQ1': {'vol': _GAS_VOL}, 'TFMBMU1': {'vol': _GAS_VOL}, 'TFMBMV1': {'vol': _GAS_VOL},
            'TFMBMX1': {'vol': _GAS_VOL}, 'TFMBMZ1': {'vol': _GAS_VOL}, 'TFMBMF2': {'vol': _GAS_VOL},
            'TFMBMG2': {'vol': _GAS_VOL}, 'TFMBMH2': {'vol': _GAS_VOL}, 'TFMBMJ2': {'vol': _GAS_VOL},
            'TFMBMK2': {'vol': _GAS_VOL}, 'TFMBMM2': {'vol': _GAS_VOL}, 'TFMBMN2': {'vol': _GAS_VOL},
            'TFMBMQ2': {'vol': _GAS_VOL}, 'TFMBMU2': {'vol': _GAS_VOL}, 'TFMBMV2': {'vol': _GAS_VOL},
            'TFMBMX2': {'vol': _GAS_VOL}, 'TFMBMZ2': {'vol': _GAS_VOL}, 'TFMBMF3': {'vol': _GAS_VOL},
            'TFMBMG3': {'vol': _GAS_VOL}, 'TFMBMH3': {'vol': _GAS_VOL}, 'TFMBMJ3': {'vol': _GAS_VOL},
            'TFMBMK3': {'vol': _GAS_VOL}, 'TFMBMM3': {'vol': _GAS_VOL}, 'TFMBMN3': {'vol': _GAS_VOL},
            'TFMBMQ3': {'vol': _GAS_VOL}, 'TFMBMU3': {'vol': _GAS_VOL}, 'TFMBMV3': {'vol': _GAS_VOL},
            'TFMBMX3': {'vol': _GAS_VOL}, 'TFMBMZ3': {'vol': _GAS_VOL}, 'TRITPSVWEND': {'vol': _GAS_VOL},
            'ICPITPSVWEND': {'vol': _GAS_VOL}, 'ICPITPSVBOW': {'vol': _GAS_VOL}, 'TRITPSVMc1': {'vol': _GAS_VOL},
            'ICPITPSVMc1': {'vol': _GAS_VOL}, 'PSVMc1': {'vol': _GAS_VOL}, 'GRFPSVMc1': {'vol': _GAS_VOL},
            'ICPITPSVBOM': {'vol': _GAS_VOL}, 'GRFPSVBOM': {'vol': _GAS_VOL}, 'TRITPSVQc1': {'vol': _GAS_VOL},
            'ICPITPSVQc1': {'vol': _GAS_VOL}, 'PSVQc1': {'vol': _GAS_VOL}, 'TRITPSVQc2': {'vol': _GAS_VOL},
            'ICPITPSVQc2': {'vol': _GAS_VOL}, 'PSVQc2': {'vol': _GAS_VOL}, 'TRITPSVQc3': {'vol': _GAS_VOL},
            'PSVQc3': {'vol': _GAS_VOL}, 'PSVQc4': {'vol': _GAS_VOL}, 'TRITPSVSc1': {'vol': _GAS_VOL},
            'ICPITPSVSc1': {'vol': _GAS_VOL}, 'PSVSc1': {'vol': _GAS_VOL}, 'TRITPSVSc2': {'vol': _GAS_VOL},
            'ICPITPSVSc2': {'vol': _GAS_VOL}, 'PSVSc2': {'vol': _GAS_VOL}, 'TRITPSVMc2': {'vol': _GAS_VOL},
            'PSVMc2': {'vol': _GAS_VOL}, 'ICPITPSVMc2': {'vol': _GAS_VOL}, 'TRITPSVMc3': {'vol': _GAS_VOL},
            'PSVMc3': {'vol': _GAS_VOL}, 'ICPITPSVMc3': {'vol': _GAS_VOL}, 'TRITPSVQc4': {'vol': _GAS_VOL},
            'TRITPSVSc3': {'vol': _GAS_VOL}, 'TRITPSVYc1': {'vol': _GAS_VOL}, 'PSVYc1': {'vol': _GAS_VOL},
            'TRITPSVYc2': {'vol': _GAS_VOL}, 'PSVYc2': {'vol': _GAS_VOL}, 'TRITPSVYc3': {'vol': _GAS_VOL},
            'PSVYc3': {'vol': _GAS_VOL}, 'TFSITPSVGDA': {'vol': _GAS_VOL}, 'TFSITPSVGWEND': {'vol': _GAS_VOL},
            'TFSITPSVGSc1': {'vol': _GAS_VOL}, 'TFSITPSVGSc2': {'vol': _GAS_VOL}, 'TFSITPSVGBOW': {'vol': _GAS_VOL},
            'TFSITPSVGMc1': {'vol': _GAS_VOL}, 'TFSITPSVGMc2': {'vol': _GAS_VOL}, 'TFSITPSVGMc3': {'vol': _GAS_VOL},
            'TFSITPSVGQc1': {'vol': _GAS_VOL}, 'TFSITPSVGQc2': {'vol': _GAS_VOL}, 'TFSITPSVGQc3': {'vol': _GAS_VOL},
            'TFSITPSVGQc4': {'vol': _GAS_VOL}, 'TFSITPSVGYc1': {'vol': _GAS_VOL}, 'TFSITPSVGYc2': {'vol': _GAS_VOL},
            'TFSITPSVGYc3': {'vol': _GAS_VOL}, 'TRBEZEED1': {'vol': _GAS_VOL}, 'TRDENCGD1': {'vol': _GAS_VOL},
            'TRFRPEGD1': {'vol': _GAS_VOL}, 'TRGBNBPWE': {'vol': _GAS_VOL}, 'TRBEZEEWE': {'vol': _GAS_VOL},
            'TRNLTTFWE': {'vol': _GAS_VOL}, 'TRDENCGWE': {'vol': _GAS_VOL}, 'TRDEGSPWE': {'vol': _GAS_VOL},
            'TRFRPEGWE': {'vol': _GAS_VOL}, 'TRGBNBPMc1': {'vol': _GAS_VOL}, 'TRBEZEEMc1': {'vol': _GAS_VOL},
            'TRNLTTFMc1': {'vol': _GAS_VOL}, 'TRDENCGMc1': {'vol': _GAS_VOL}, 'TRDEGSPMc1': {'vol': _GAS_VOL},
            'TRFRPEGMc1': {'vol': _GAS_VOL}, 'TRGBNBPMc2': {'vol': _GAS_VOL}, 'TRBEZEEMc2': {'vol': _GAS_VOL},
            'TRNLTTFMc2': {'vol': _GAS_VOL}, 'TRDENCGMc2': {'vol': _GAS_VOL}, 'TRDEGSPMc2': {'vol': _GAS_VOL},
            'TRFRPEGMc2': {'vol': _GAS_VOL}, 'TRGBNBPMc3': {'vol': _GAS_VOL}, 'TRBEZEEMc3': {'vol': _GAS_VOL},
            'TRNLTTFMc3': {'vol': _GAS_VOL}, 'TRDENCGMc3': {'vol': _GAS_VOL}, 'TRDEGSPMc3': {'vol': _GAS_VOL},
            'TRFRPEGMc3': {'vol': _GAS_VOL}, 'TRGBNBPQc1': {'vol': _GAS_VOL}, 'TRBEZEEQc1': {'vol': _GAS_VOL},
            'TRNLTTFQc1': {'vol': _GAS_VOL}, 'TRDENCGQc1': {'vol': _GAS_VOL}, 'TRDEGSPQc1': {'vol': _GAS_VOL},
            'TRFRPEGQc1': {'vol': _GAS_VOL}, 'TRGBNBPQc2': {'vol': _GAS_VOL}, 'TRBEZEEQc2': {'vol': _GAS_VOL},
            'TRNLTTFQc2': {'vol': _GAS_VOL}, 'TRDENCGQc2': {'vol': _GAS_VOL}, 'TRDEGSPQc2': {'vol': _GAS_VOL},
            'TRFRPEGQc2': {'vol': _GAS_VOL}, 'TRGBNBPQc3': {'vol': _GAS_VOL}, 'TRBEZEEQc3': {'vol': _GAS_VOL},
            'TRNLTTFQc3': {'vol': _GAS_VOL}, 'TRDENCGQc3': {'vol': _GAS_VOL}, 'TRDEGSPQc3': {'vol': _GAS_VOL},
            'TRFRPEGQc3': {'vol': _GAS_VOL}, 'TRGBNBPSc1': {'vol': _GAS_VOL}, 'TRBEZEESc1': {'vol': _GAS_VOL},
            'TRNLTTFSc1': {'vol': _GAS_VOL}, 'TRDENCGSc1': {'vol': _GAS_VOL}, 'TRDEGSPSc1': {'vol': _GAS_VOL},
            'TRFRPEGSc1': {'vol': _GAS_VOL}, 'TRGBNBPSc2': {'vol': _GAS_VOL}, 'TRBEZEESc2': {'vol': _GAS_VOL},
            'TRNLTTFSc2': {'vol': _GAS_VOL}, 'TRDENCGSc2': {'vol': _GAS_VOL}, 'TRDEGSPSc2': {'vol': _GAS_VOL},
            'TRFRPEGSc2': {'vol': _GAS_VOL}, 'TRNLTTFYc1': {'vol': _GAS_VOL}, 'TRDENCGYc1': {'vol': _GAS_VOL},
            'TRDEGSPYc1': {'vol': _GAS_VOL}, 'TRFRPEGYc1': {'vol': _GAS_VOL}, 'TRNLTTFYc2': {'vol': _GAS_VOL},
            'TRDENCGYc2': {'vol': _GAS_VOL}, 'TRDEGSPYc2': {'vol': _GAS_VOL}, 'TRFRPEGYc2': {'vol': _GAS_VOL}}
