gas_rics = {'TRITPSVDA': None, 'TRITPSVWEND': None, 'ICPITPSVWEND': None, 'ICPITPSVBOW': None, 'TRITPSVMc1': None,
            'ICPITPSVMc1': None, 'PSVMc1': None, 'GRFPSVMc1': None, 'ICPITPSVBOM': None, 'GRFPSVBOM': None,
            'TRITPSVQc1': None, 'ICPITPSVQc1': None, 'PSVQc1': None, 'TRITPSVQc2': None, 'ICPITPSVQc2': None,
            'PSVQc2': None, 'TRITPSVQc3': None, 'PSVQc3': None, 'PSVQc4': None, 'TRITPSVSc1': None, 'ICPITPSVSc1': None,
            'PSVSc1': None, 'TRITPSVSc2': None, 'ICPITPSVSc2': None, 'PSVSc2': None, 'TRITPSVMc2': None, 'PSVMc2': None,
            'ICPITPSVMc2': None, 'TRITPSVMc3': None, 'PSVMc3': None, 'ICPITPSVMc3': None, 'TRITPSVQc4': None,
            'TRITPSVSc3': None, 'TRITPSVYc1': None, 'PSVYc1': None, 'TRITPSVYc2': None, 'PSVYc2': None,
            'TRITPSVYc3': None, 'PSVYc3': None, 'TRGBNBPD1': None, 'TRBEZEED1': None, 'TRNLTTFD1': None,
            'TRDENCGD1': None, 'TRDEGSPD1': None, 'TRFRPEGD1': None, 'CGXHVPDA': None, 'TRGBNBPWE': None,
            'TRBEZEEWE': None, 'TRNLTTFWE': None, 'TRDENCGWE': None, 'TRDEGSPWE': None, 'TRFRPEGWE': None,
            'TRGBNBPMc1': None, 'TRBEZEEMc1': None, 'TRNLTTFMc1': None, 'TRDENCGMc1': None, 'TRDEGSPMc1': None,
            'TRFRPEGMc1': None, 'TRGBNBPMc2': None, 'TRBEZEEMc2': None, 'TRNLTTFMc2': None, 'TRDENCGMc2': None,
            'TRDEGSPMc2': None, 'TRFRPEGMc2': None, 'TRGBNBPMc3': None, 'TRBEZEEMc3': None, 'TRNLTTFMc3': None,
            'TRDENCGMc3': None, 'TRDEGSPMc3': None, 'TRFRPEGMc3': None, 'TRGBNBPQc1': None, 'TRBEZEEQc1': None,
            'TRNLTTFQc1': None, 'TRDENCGQc1': None, 'TRDEGSPQc1': None, 'TRFRPEGQc1': None, 'TRGBNBPQc2': None,
            'TRBEZEEQc2': None, 'TRNLTTFQc2': None, 'TRDENCGQc2': None, 'TRDEGSPQc2': None, 'TRFRPEGQc2': None,
            'TRGBNBPQc3': None, 'TRBEZEEQc3': None, 'TRNLTTFQc3': None, 'TRDENCGQc3': None, 'TRDEGSPQc3': None,
            'TRFRPEGQc3': None, 'TRGBNBPSc1': None, 'TRBEZEESc1': None, 'TRNLTTFSc1': None, 'TRDENCGSc1': None,
            'TRDEGSPSc1': None, 'TRFRPEGSc1': None, 'TRGBNBPSc2': None, 'TRBEZEESc2': None, 'TRNLTTFSc2': None,
            'TRDENCGSc2': None, 'TRDEGSPSc2': None, 'TRFRPEGSc2': None, 'TRNLTTFYc1': None, 'TRDENCGYc1': None,
            'TRDEGSPYc1': None, 'TRFRPEGYc1': None, 'TRNLTTFYc2': None, 'TRDENCGYc2': None, 'TRDEGSPYc2': None,
            'TRFRPEGYc2': None, 'CZVTPDA': None, 'CZVTPMc1': None, 'CZVTPMc2': None, 'CZVTPMc3': None, 'CZVTPQc1': None,
            'CZVTPQc2': None, 'CZVTPQc3': None, 'CZVTPQc4': None, 'CZVTPSc1': None, 'CZVTPSc2': None, 'CZVTPWDNW': None,
            'CZVTPWE': None, 'CZVTPYc1': None, 'CZVTPYc2': None, 'CZVTPYc3': None, 'GRFCZVTPBOM': None,
            'ICPATVTPDA': None, 'ICPATVTPWED': None, 'ICPATVTPBOW': None, 'ICPATVTPWNW': None, 'ICPATVTPMc1': None,
            'ICPATVTPMc2': None, 'ICPATVTPMc3': None, 'ICPATVTPBOM': None, 'ICPATVTPQc1': None, 'ICPATVTPQc2': None,
            'ICPATVTPQc3': None, 'ICPATVTPQc4': None, 'ICPATVTPSc1': None, 'ICPATVTPSc2': None, 'ICPATVTPYc1': None,
            'ICPATVTPYc2': None, 'ICPATVTPYc3': None}
